language: node_js
node_js:
  - 'node'
  - '10'
before_install:
  - npm install -g coveralls
install:
  - npm install
script:
  - npm run coverage
after_script:
  - cat ./coverage/lcov.info | coveralls